#!/bin/bash
# Maintainer: Fatih BOSTANCI <faopera@gmail.com>

echo "güncel değil"; exit 1
pkgname=ezanvakti
pkgver=6.2
startdir="$(pwd)"
srcdir="$startdir/src"
pkgdir="$startdir/pkg"
makedepends=('devscripts' 'fakeroot' 'debhelper')

BOLD=$(tput bold)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
RED=$(tput setaf 1)
ALL_OFF=$(tput sgr0)

trap ctrlc INT

function msg() {
  local ilt=$1; shift
  printf "${GREEN}==>${ALL_OFF}${BOLD} ${ilt}${ALL_OFF}\n" "$@" >&2
}

function msg2() {
  local ilt=$1; shift
  printf "${BLUE}==>${ALL_OFF}${BOLD} ${ilt}${ALL_OFF}\n" "$@" >&2
}

function error() {
  local ilt=$1; shift
  printf "${RED}==> HATA:${ALL_OFF}${BOLD} ${ilt}${ALL_OFF}\n" "$@" >&2
  exit 1
}

function ctrlc() {
  echo
  error "Kullanıcı tarafından işlem iptal edildi"; exit 1
}

# root olarak çalıştırılmasın.
[[ $UID -eq 0 ]] && error "Yönetici haklarıyla çalıştırılmaz.."

function build() {
  mkdir -p "$startdir"/{src,pkg} && cd "$startdir/src"
  msg "Gitorious GIT sunucusuna bağlanılıyor..."

  if [ -d "$startdir/src/$_gitname" ]
  then
      cd $_gitname && git pull origin && cd -
  else
      git clone "$_gitroot"
  fi

  msg "Ubuntu özelleştirme yaması uygulanıyor..."
  cd "$srcdir"/$pkgname
  patch -p1 -i ubuntu-ozl.patch
  cd -
}

function package() {
  msg ".deb paketi oluşturuluyor..."
  debuild -us -uc
}

function mk_dep_control() {
  msg2 "Paketlemek için gerekli bağımlılıklar denetleniyor..."
  for i in ${makedepends[@]}
  do
      [[ ! $(type -p $i) ]] && error "Devam etmek için $i paketini kurun..."
  done
  msg "TAMAM"
  return 0
}

mk_dep_control && build && package
