.TH "Ezanvakti" "1" "2017\-07\-07" "Ezanvakti 6\&.3" "Ezanvakti Kullanım Yönergeleri"
.SH "AD"
Ezanvakti 6\.3 \- GNU/Linux için Ezan Vakti Bildirici
.SH "KULLANIM ŞEKLİ"
.B ezanvakti
.RI [ seçenek ]
.SH AÇIKLAMA
Diyanet İşleri Başkanlığı sitesinden
.B (http://www.diyanet.gov.tr)
bulunduğunuz ülke ve şehre ait aylık namaz vakitlerini kullanarak,
zamanı geldiğinde ezan okuyan ve bildirim veren bir uygulamadır.
Ayrıca istenilen zaman ezan ve çevrimiçi Kuran-ı Kerim dinleme,
ezan vakitlerine ne kadar süre kaldığını gösterme, kerahat vakitlerini
gösterme gibi ek özellikleri vardır. Kullanılan dosyaları yapılandırma
dosyasından okuduğundan kullanıcıya daha fazla özelleştirme sunar.
.SH SEÇENEKLER
.TP
.B \-v, \-\-v, \-\-vakitler
Toplu olarak günlük ezan vakitlerini görüntüler ve vakitlere ne kadar süre
kaldığını gösterir ve çıkar. Eğer vakit geçmişse "OKUNDU" olarak görünür.
.PP
Vakit gösterimi sık kullanılacak bir komut olduğu için birleşik kullanımı da
vardır.
.TP 5
.B \      -vs, \-\-vs
Sabah vakti gösterimi için birleşik komuttur.
.TP 5
.B \      -vo, \-vö, \-\-vo, \-\-vö
Öğle vakti gösterimi için birleşik komuttur.
.TP 5
.B \      -vi, \-\-vi
İkindi vakti gösterimi için birleşik komuttur.
.TP 5
.B \      -va, \-\-va
Akşam vakti gösterimi için birleşik komuttur.
.TP 5
.B \      -vy, \-\-vy
Yatsı vakti gösterimi için birleşik komuttur.
.TP 5
.B \      -vk, \-\-vk
Kerahat vakitleri gösterimi için birleşik komuttur.
.TP 5
.B \      -v7, \-\-v7
7 günlük vakit gösterimi için birleşik komuttur.
.TP 5
.B \      -v30, \-\-v30
30 günlük vakit gösterimi için birleşik komuttur.
.TP 5
.B \      -vb, \-\-vb
Vakitler çıktısının bildirim baloncuğunda
gösterimi için birleşik komuttur.
.TP 5
.B \      -vt, \-\-vt
Sıradaki vakit ve vakte ne kadar süre kaldığının
gösterimi için birleşik komuttur.
.PP
\fInormal kullanımlar için ek olarak\fP :
.TP 5
.B \      -s, \-\-sabah
Sabah vaktine ne kadar süre kaldığını gösterir ve çıkar.
.TP 5
.B \      -o, \-\-ogle, \-\-öğle
Öğle vaktine ne kadar süre kaldığını gösterir ve çıkar.
.TP 5
.B \      -i, \-\-ikindi
İkindi vaktine ne kadar süre kaldığını gösterir ve çıkar.
.TP 5
.B \      -a, \-\-aksam, \-\-akşam
Akşam vaktine ne kadar süre kaldığını gösterir ve çıkar.
.TP 5
.B \      -y, \-\-yatsi, \-\-yatsı
Yatsı vaktine ne kadar süre kaldığını gösterir ve çıkar.
.TP 5
.B \      -k, \-\-kerahat
Bulunduğunuz yer için o güne ait kerahat vakitlerini gösterir ve çıkar.
.TP 5
.B \      7, \-\-haftalik, \-\-haftalık
7 günlük vakitleri listeler ve çıkar.
.TP 5
.B \      30, \-\-aylik, \-\-aylık
30 günlük vakitleri listeler ve çıkar.
.TP 5
.B \     \-\-osd, \-\-bildirim
Vakitler çıktısını uçbirim yerine bildirim baloncuğuna yönlendirir.
.TP 5
.B \      -t, \-\-sıradaki, \-\-siradaki
Sıradaki vakit ve vakte ne kadar süre kaldığını gösterir ve çıkar.
.TP
.B \-\-kuran \fI[ek_seçenek]\fP
Çevrimiçi olarak ya da yerel dizinden Kuran-ı Kerim dinletir. Çevrimiçi Kuran-ı Kerim dinleme
için listen2quran.com sitesi kullanılmaktadır. Kuran dinlemek
için ek olarak aşağıdakilerden uygun seçeneği de girmeniz
gereklidir.
.TP
Kuran dinletimi için de birleşik komut desteği vardır.
.TP 5
.B \      -ks, \-\-ks
Değişken olarak \fI<sure_kodu>\fP verildiğinde o kodla ilişik sureyi dinletir.
.TP 5
.B \      -kr, \-\-kr
1-114 arası rastgele bir sure seçip dinletmenin birleşik komutudur.
.TP 5
.B \      -kh, \-\-kh
1'den 114'e kadar tüm sureleri sırayla okumanın birleşik komutudur.
.TP 5
.B \      -kg, \-\-kg
\'ayarlar' dosyasında SURELER için girilen numaralara ait sureleri dinletmenin
birleşik komutudur.
.TP
\fInormal kullanımlar için ek olarak\fP :
.TP 5
.B \      -s, \-\-secim, \-\-seçim
Değişken olarak \fI<sure_kodu>\fP verildiğinde o kodla ilişik sureyi dinletir.
.TP 5
.B \      -r, \-\-rastgele
1-114 arası rastgele bir sure seçer ve dinletir.
.TP 5
.B \      -h, \-\-hatim
1'den 114'e kadar tüm sureleri sırayla okur.
.TP 5
.B \      -g, \-\-gunluk, \-\-günlük
\'ayarlar' dosyasında SURELER için girilen numaralara ait sureleri dinletir ve çıkar.
.TP
.B \-\-sureler
Sureleri dinlemek için gerekli olan kod numaralarını ve sure adlarını görüntüler ve çıkar.
.TP
.B \-\-ayet
Rastgele bir Kuran-ı Kerim ayeti seçerek Türkçe anlamını uçbirimde gösterir.
.PP
\fIek olarak\fP
.TP 5
.B \      -b, \-o, \-\-bildirim, \-\-osd
Ayeti uçbirim yerine bildirim baloncuğunda görüntüler ve çıkar.
.TP
.B \-\-iftar
İftar vaktine ne kadar süre kaldığını görüntüler ve çıkar.
.TP
.B \-\-conky
Conky alanına günlük ezan vakitlerini eklemek isteyenler için renksiz
ve kısa çıktı verir.
.TP
\fIek olarak\fP
.TP 5
.B \      i, \-\-iftar
Conky alanında iftar vaktine ne kadar süre kaldığını görmek isteyenler için
renksiz ve kısa çıktı verir.
.TP
.B \      -s, \-\-sıradaki, \-\-siradaki
Conky alanında sıradaki vakit ve vakte ne kadar süre kaldığını görmek isteyenler için
renksiz ve kısa çıktı verir.
.TP
.B \      -k, \-\-kerahat
Conky alanında, o güne ait kerahat vakitlerini görmek isteyenler için renksiz ve kısa
çıktı verir.
.TP
.B \-\-aralık, \-\-aralik \fI[sure_kodu] [ayet_aralıgı_başlangıç-ayet_aralığı_bitiş]\fR
Ayet gösteriminde istenen surenin istenen ayet aralığını gösterir.
ör: ezanvakti \-\-aralık \2 \55\-\61 \2. surenin \55. ve \61. ayetleri dahil olmak üzere aradaki ayetleri gösterir.
.TP
.B \-\-dinle \fI[ek_seçenek]\fP
istediğiniz zaman istediğiniz vakite ait ezanı dinletir. Dinlemek istediğiniz
vakit için girmeniz gereken ek seçenekler:
.TP 5
.B \      -s, \-\-sabah
Sabah ezanını dinletir.
.TP 5
.B \      -o, \-ö, \-\-ogle, \-\-öğle
Öğle ezanını dinletir.
.TP 5
.B \      -i, \-\-ikindi
İkindi ezanını dinletir.
.TP 5
.B \      -a, \-\-aksam, \-\-akşam
Akşam ezanını dinletir.
.TP 5
.B \      -y, \-\-yatsi, \-\-yatsı
Yatsı ezanını dinletir.
.TP
.B \-\-hadis
40 hadisten rastgele bir hadis seçerek uçbirimde gösterir.
.PP
\fIek olarak\fP
.TP 5
.B \      -b, \-o, \-\-bildirim, \-\-osd
Hadisi uçbirim yerine bildirim baloncuğunda görüntüler ve çıkar.
.TP
.B \-\-esma
Esma-ül Hüsna olarak adlandırılan Allah'ın güzel adlarından 99 tane içinden
rastgele bir seçim yapar ve seçileni \fIyalnızca\fP uçbirimde gösterir.
.TP
.B \-\-bilgi
Diyanet sitesinden alınan "Bunları biliyor musunuz?" adlı içerikten rastgele
bir soru seçerek, sorunun yanıtıyla beraber, uçbirimde gösterir.
.PP
\fIek olarak\fP
.TP 5
.B \      -b, \-o, \-\-bildirim, \-\-osd
Soru ve yanıtı uçbirim yerine bildirim baloncuğunda görüntüler ve çıkar.
.TP
.B \-\-gunler, \-\-günler
İçinde bulunduğunuz yıla ait dini günler ve geceleri liste halinde görüntüler ve çıkar.
.TP
.B  \-\-arayuz, \-\-arayüz, \-\-gui
Ezanvakti gelişmiş arayüz bileşenini başlatır.
.TP
.B  \-\-arayuz2, \-\-arayüz2, \-\-gui2
Ezanvakti basit arayüz bileşenini başlatır.
.TP
.B \ -\-guncelle, \-\-güncelle
Ezanveri dosyasını 30 günlük vakitleri içerecek şekilde günceller/ oluşturur.
Mevcut ezanveri dosyanızın adını ve konumunu ayrıca bulunduğunuz ülke ve şehri 'ayarlar'
dosyasından okur ve günceller. Ülke ve şehir olarak girilen değerler güncellenme için kullanılan
dosyalardaki gibi yazılmamışsa, ekrana bulunduğunuz ülke ve şehri soran pencereler çıkar
ve seçilen ülke ve şehre göre işlem yapar. Aynı zamanda bir sonraki güncelleme işlemlerini
kolaylaştırmak adına 'ayarlar' dosyanıza seçtiğiniz ülke ve şehir adını işler.


Veriler diyanet.gov.tr sitesi üzerinden alınmaktadır.
.TP
.B \-\-renk, \-\-renk-ogren, \-\-renk-öğren
Uçbirim ekranında renklerin kodlarını o kodun nasıl göründüğünü toplu şekilde gösterir.
Özellikle ayarlar dosyasındaki uçbirim renklerini değiştirme işleminde kullanıcıya kolaylık
sağlar.
.TP
.B \-\-config, \-\-yapılandırma, \-\-yapilandirma
ayarlar dosyasını uçbirim ekranında açar. Açma işlemi için EDITOR tanımlı uygulamayı kullanır.
EDITOR tanımlı değilse nano ile açar.
.TP
.B \-\-kalan
Uçbirim ekranında özyinelemeli olarak sıradaki vakti ve vakte ne kadar süre kaldığını gösterir.
.TP
.B  \-\-surum, \-\-sürüm, \-\-version, \-V
Ezanvakti uygulamasının sürüm bilgisini görüntüler ve çıkar.
.TP
.B  \-\-yardım, \-\-yardim, \-\-help, \-h
Yardım bilgisini gösterir ve çıkar.
.LP
.SH YAZAR
	Fatih Bostancı <faopera@gmail.com>

	distroguide.wordpress.com
